/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/layouts/BaseLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    GlobalConfirmDialog: typeof import('./src/components/common/GlobalConfirmDialog.vue')['default']
    HeaderLayout: typeof import('./src/components/layouts/HeaderLayout.vue')['default']
    IconAlmoxarifado: typeof import('./src/components/icons/IconAlmoxarifado.vue')['default']
    IconCompras: typeof import('./src/components/icons/IconCompras.vue')['default']
    IconContabilidade: typeof import('./src/components/icons/IconContabilidade.vue')['default']
    IconControleInterno: typeof import('./src/components/icons/IconControleInterno.vue')['default']
    IconDepartamentoPessoal: typeof import('./src/components/icons/IconDepartamentoPessoal.vue')['default']
    IconDiarias: typeof import('./src/components/icons/IconDiarias.vue')['default']
    IconFrota: typeof import('./src/components/icons/IconFrota.vue')['default']
    IconOrcamento: typeof import('./src/components/icons/IconOrcamento.vue')['default']
    IconPatrimonio: typeof import('./src/components/icons/IconPatrimonio.vue')['default']
    IconRequisicaoInterna: typeof import('./src/components/icons/IconRequisicaoInterna.vue')['default']
    IconTesouraria: typeof import('./src/components/icons/IconTesouraria.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sh3Banner: typeof import('./src/components/common/Sh3Banner.vue')['default']
    Sh3Button: typeof import('./src/components/common/Sh3Button.vue')['default']
    Sh3Card: typeof import('./src/components/common/Sh3Card.vue')['default']
    Sh3ConfirmDialog: typeof import('./src/components/common/Sh3ConfirmDialog.vue')['default']
    Sh3EmptyState: typeof import('./src/components/common/state/Sh3EmptyState.vue')['default']
    Sh3ErrorState: typeof import('./src/components/common/state/Sh3ErrorState.vue')['default']
    Sh3Form: typeof import('./src/components/common/Sh3Form.vue')['default']
    Sh3GridList: typeof import('./src/components/common/Sh3GridList.vue')['default']
    Sh3LoadingState: typeof import('./src/components/common/state/Sh3LoadingState.vue')['default']
    Sh3Message: typeof import('./src/components/common/Sh3Message.vue')['default']
    Sh3Modal: typeof import('./src/components/common/Sh3Modal.vue')['default']
    Sh3ProgressSpinner: typeof import('./src/components/common/Sh3ProgressSpinner.vue')['default']
    Sh3Search: typeof import('./src/components/common/Sh3Search.vue')['default']
    Sh3Select: typeof import('./src/components/common/Sh3Select.vue')['default']
    Sh3StatsGrid: typeof import('./src/components/common/Sh3StatsGrid.vue')['default']
    Sh3Table: typeof import('./src/components/common/Sh3Table.vue')['default']
    Sh3Tag: typeof import('./src/components/common/Sh3Tag.vue')['default']
    Sh3ToggleSwitch: typeof import('./src/components/common/Sh3ToggleSwitch.vue')['default']
    Sh3Welcome: typeof import('./src/components/common/Sh3Welcome.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    SuiteHome: typeof import('./src/components/SuiteHome.vue')['default']
    ThemeSwitcher: typeof import('./src/components/theme/ThemeSwitcher.vue')['default']
  }
}
