/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutarquiaSelect: typeof import('./src/components/select/AutarquiaSelect.vue')['default']
    BaseLayout: typeof import('./src/components/layouts/BaseLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    GenericForm: typeof import('./src/components/common/GenericForm.vue')['default']
    GenericTable: typeof import('./src/components/common/GenericTable.vue')['default']
    IconAlmoxarifado: typeof import('./src/components/icons/IconAlmoxarifado.vue')['default']
    IconCompras: typeof import('./src/components/icons/IconCompras.vue')['default']
    IconContabilidade: typeof import('./src/components/icons/IconContabilidade.vue')['default']
    IconControleInterno: typeof import('./src/components/icons/IconControleInterno.vue')['default']
    IconDepartamentoPessoal: typeof import('./src/components/icons/IconDepartamentoPessoal.vue')['default']
    IconDiarias: typeof import('./src/components/icons/IconDiarias.vue')['default']
    IconFrota: typeof import('./src/components/icons/IconFrota.vue')['default']
    IconOrcamento: typeof import('./src/components/icons/IconOrcamento.vue')['default']
    IconPatrimonio: typeof import('./src/components/icons/IconPatrimonio.vue')['default']
    IconRequisicaoInterna: typeof import('./src/components/icons/IconRequisicaoInterna.vue')['default']
    IconTesouraria: typeof import('./src/components/icons/IconTesouraria.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    SuiteHome: typeof import('./src/components/SuiteHome.vue')['default']
    SuiteItems: typeof import('./src/components/SuiteItems.vue')['default']
    ThemeSwitcher: typeof import('./src/components/theme/ThemeSwitcher.vue')['default']
    UserForm: typeof import('./src/components/usuario/UserForm.vue')['default']
    UserTable: typeof import('./src/components/usuario/UserTable.vue')['default']
    UsuarioCard: typeof import('./src/components/usuario/UsuarioCard.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
